### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by TanDongXu** [ilyakava/ciresan#1]
hi ,
I have already installed the environment.but when I use the command "python code/ciresan2012.py 128 20 1 1 0.2" to train,there is an  error  occurred as follow:

Traceback (most recent call last):
  File "code/ciresan2012.py", line 383, in <module>
    distortion=distortion, n_epochs=n_epochs, cuda_convnet=cuda_convnet, conserve_gpu_memory=conserve_gpu_memory)
  File "code/ciresan2012.py", line 363, in train_ciresan2012
    datasets = load_data(dataset, normalized_width, out_image_size=29, conserve_gpu_memory=conserve_gpu_memory)
TypeError: load_data() got an unexpected keyword argument 'out_image_size'

I don't know why.could you help me solve the problem? thanks

**Comment by ilyakava** [comment]
Thanks for posting the issue!

I just fixed this [here](https://github.com/ilyakava/ciresan/commit/bfb4447c5b4469f7907e548501ede61f30ad170e) it was the result of a typo after a refactor.

I just tested `python code/ciresan2012.py 128 20 1 1 0.2` on a gpu and it works again. If you pull from master again the problem will go away :)

Thank you!

**Comment by TanDongXu** [comment]
The problem has been solved, thank you very much.
